### ISSUE TITLE
FailedToFetchRemoteImageDimensions[v4.7]

### ISSUE THREAD

**Issue by oregonpillow** [isooosi/VisVrs#77]
After doing a complete new clone of v4.7 and installing dependencies, i'm running the dev server and clicking around i get this error:

![Screenshot 2024-05-06 at 19 59 28](https://github.com/isooosi/VisVrs/assets/53374403/1c9b033d-9287-46bc-bcfb-c08debee8ac7)

**Comment by oregonpillow** [comment]
Problem seems limited to dev server. Goes away when using `pnpm run build` + `pnpm run preview`

**Comment by oregonpillow** [comment]
nvm. issue still happening using run preview:

```
20:13:05   ├─ /posts/components7/index.html[FailedToFetchRemoteImageDimensions] Failed to get the dimensions for https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8YmxhY2t8ZW58MHwwfDB8fHwy.
  Hint:
    Verify your remote image URL is accurate, and that you are not using `inferSize` with a file located in your `public/` folder.
  Error reference:
    https://docs.astro.build/en/reference/errors/failed-to-fetch-remote-image-dimensions/
  Stack trace:
    at getImage$1 (file:///home/user1/VisVrs/dist/chunks/1715019182642/FormattedDate.mjs:862:13)
    at async getImage (file:///home/user1/VisVrs/dist/chunks/1715019182642/FormattedDate.mjs:981:42)
    at async AstroComponentInstance.render (file:///home/user1/VisVrs/dist/chunks/1715019182642/astro/server.mjs:924:7)
    at async renderChild (file:///home/user1/VisVrs/dist/chunks/1715019182642/astro/server.mjs:875:5)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by isooosi** [comment]
```
## Important Notice

**Project Refactoring Alert:** This project has undergone extensive refactoring, which may cause issues with dependencies and the build process. To ensure the project runs smoothly, please follow these steps:

1. Delete the old node_modules folder:

```bash
rm -rf node_modules
```

2. Clear the cache:

```bash
pnpm cache clear --force
```

3. Reinstall dependencies:

```bash
pnpm install
```

These steps will ensure that you are using the latest dependencies and help avoid any issues arising from the refactoring. If you encounter any problems during usage, feel free to submit an issue for prompt resolution. Thank you for your understanding and support!
```
